---
environment: "staging"
cluster_name: "evm-blockchain-staging-cluster"
notification_channels:
  infrastructure:
    ecs: "slack-dd-ecs-alerts-p2"
    alb: "slack-dd-elb-alerts-p2"
    rds: "slack-dd-rds-alerts-p2"
  messaging:
    sns: "slack-dd-sns-alerts-p2"
    sqs: "slack-dd-sqs-alerts-p2"
  application:
    java: "slack-dd-apm-alerts-p2"
    node: "slack-dd-apm-alerts-p2"
    apm: "slack-dd-apm-alerts-p2"
  logs: "slack-dd-logs-alerts-p2"
  default: "slack-dd-ecs-alerts-p2"

threshold_overrides:
  infrastructure:
    ecs:
      evm-blockchain-arceus:
        cpu_percent: 85
        memory_percent: 90
        memory_available: 1024
        network_errors: 20
        alert_settings:
          priority: "3"
          include_tags: true
      evm-blockchain-gateway:
        cpu_percent: 85
        memory_percent: 90
        memory_available: 1024
        network_errors: 20
        alert_settings:
          priority: "3"
          include_tags: true
      evm-blockchain-signer:
        cpu_percent: 85
        memory_percent: 90
        memory_available: 1024
        network_errors: 20
        alert_settings:
          priority: "3"
          include_tags: true
      solana-provider-arceus:
        cpu_percent: 85
        memory_percent: 90
        memory_available: 1024
        network_errors: 20
        alert_settings:
          priority: "3"
          include_tags: true
      solana-provider-gateway:
        cpu_percent: 85
        memory_percent: 90
        memory_available: 1024
        network_errors: 20
        alert_settings:
          priority: "3"
          include_tags: true
      solana-provider-signer:
        cpu_percent: 85
        memory_percent: 90
        memory_available: 1024
        network_errors: 20
        alert_settings:
          priority: "3"
          include_tags: true
    alb:
      blockchain-providers:
        enabled: false
  application:
    node:
      enabled: true
      services:
        evm-blockchain-arceus:
          alert_settings:
            priority: "3"
        evm-blockchain-gateway:
          alert_settings:
            priority: "3"
        evm-blockchain-signer:
          alert_settings:
            priority: "3"
        solana-provider-arceus:
          alert_settings:
            priority: "3"
        solana-provider-gateway:
          alert_settings:
            priority: "3"
        solana-provider-signer:
          alert_settings:
            priority: "3"
  logs:
    services:
      evm-blockchain-arceus:
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
      evm-blockchain-gateway:
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
      evm-blockchain-signer:
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
      solana-provider-arceus:
        custom_log_lines:
          - "ViemException: transaction.insufficient-funds"
          - "ViemException: prepare-transaction"
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
      solana-provider-gateway:
        custom_log_lines:
          - "ViemException: transaction.insufficient-funds"
          - "ViemException: prepare-transaction"
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
      solana-provider-signer:
        custom_log_lines:
          - "ViemException: transaction.insufficient-funds"
          - "ViemException: prepare-transaction"
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
        alert_settings:
          priority: "3"
          include_tags: true
