---
environment: "staging"
cluster_name: "api-gateway-staging-cluster"
notification_channels:
  infrastructure:
    ecs: "slack-dd-ecs-alerts-p2"
    alb: "slack-dd-elb-alerts-p2"
    rds: "slack-dd-rds-alerts-p2"
  messaging:
    sns: "slack-dd-sns-alerts-p2"
    sqs: "slack-dd-sqs-alerts-p2"
  application:
    java: "slack-dd-apm-alerts-p2"
    node: "slack-dd-apm-alerts-p2"
    apm: "slack-dd-apm-alerts-p2"
  default: "slack-dd-ecs-alerts-p2"
  logs: "slack-dd-logs-alerts-p2"

threshold_overrides:
  infrastructure:
    ecs:
      api-gateway:
        cpu_percent: 90
        memory_percent: 90
        memory_available: 1024
        network_errors: 10
        alert_settings:
          priority: "4"
    alb:
      api-gateway:
        enabled: false
    db:
      enabled: false
  messaging:
    sqs:
      enabled: false
    sns:
      enabled: false
  application:
    apm:
      enabled: true
      services:
        api-gateway:
          thresholds:
            latency: 150
            error_rate: 5
            throughput: 90
          alert_settings:
            priority: "4"
    java:
      enabled: true
      services:
        api-gateway:
          jvm:
            thresholds:
              jvm_memory_used: 2048
            alert_settings:
              priority: "3"
  logs:
    services:
      api-gateway:
        thresholds:
          critical: 30
          critical_recovery: 25
          warning: 20
          warning_recovery: 15
